{
  "c2_server": true,
  "web_interface": false,
  "payload_started": true,
  "api": {
    "error": "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a916f130>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  }
}